version: 2.1

defaults: &defaults
  working_directory: ~/auto-demo
  docker:
    - image: circleci/node:latest-browsers

jobs:
  release:
    <<: *defaults
    steps:
      - checkout
      - run: npm ci
      - run: npx auto shipit
  pr_check:
    <<: *defaults
    steps:
      - run: npx auto pr-check --url ${CIRCLE_BUILD_URL}

workflows:
  build_and_release:
    jobs:
      - release
      - pr_check:
          filters:
            branches:
              ignore:
                - master
